# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_base_link1:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  joint_link1_link2:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  joint_link2_link3:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  joint_link3_link4:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  joint_link4_link5:
    has_velocity_limits: true
    max_velocity: 5.23
    has_acceleration_limits: false
    max_acceleration: 0
  joint_link5_endeffector:
    has_velocity_limits: true
    max_velocity: 5.23
    has_acceleration_limits: false
    max_acceleration: 0